### ISSUE TITLE
Crash loop

### ISSUE THREAD

**Issue by 1flyr** [retronbv/buffy#23]
Buffy crash loops for me in replit. Is there a way to fix this.

**Comment by retronbv** [comment]
I just created a new repl using this repo, no crash loop and it works perfectly fine. Try creating the repl again? Could you send me the link to the repl you are using?

**Comment by 1flyr** [comment]
https://buffy-1.flufymalware.repl.co
this is the compiled one

https://replit.com/@flufymalware/buffy-1
this is the replit code

**Comment by retronbv** [comment]
i think youtube just isnt supported bro

**Comment by retronbv** [comment]
try just using an invidious instance
