### ISSUE TITLE
When a link opens in a new tab it is no longer proxied

### ISSUE THREAD

**Issue by OddPvP** [retronbv/buffy#8]
This breaks most sites please fix this as soon as possible.

**Comment by nxxh447** [comment]
i mean what did you expect

**Comment by retronbv** [comment]
Ill look into it... could you give me some sites that don't work?

**Comment by OddPvP** [comment]
yandex.com when I click on the games section

**Comment by Animationking11** [comment]
When will this be fixed?

**Comment by OddPvP** [comment]
> Ill look into it... could you give me some sites that don't work?

Can I have an ETA for when this will be fixed?

**Comment by retronbv** [comment]
This is not a bug with the proxy, it is currently only built to proxy **one** website. So, https://yandex.com linking to https://games.yandex.com is not going to work very well.. In a future update we will support more than one site in the proxy
